# Logo
logo_image_source: /images/2017/07/CODE-WITHSTYLE-1.png

# Index Page
index_banner_text: Code with Style!
index_banner_text_secondary: Web Development & Functional Programming.
index_font_awesome_icon_css:
# Header
menu:
  Table of Contents: /toc
  TypeScript: /tags/typescript
  Functional Programming: /functional-programming
  Author: http://miloszpiechocki.com/

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fas fa-folder-open

# About Widget
about_widget_avatar_url: /images/speaker-avatar-2.png
about_widget_text: "Hi! My name is Miłosz Piechocki. I’m a software developer living in Warsaw, Poland. I’m passionate about TypeScript, JavaScript and functional programming in modern web development."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: codewithstyle

# Google Analytics Tracking ID
google_analytics: UA-89535231-1

# Social Media Platforms
social_platforms:
  - url: http://twitter.com/miloszpp/
    fa_icon: fab fa-twitter
  - url: http://facebook.com/codewithstyle.info/
    fa_icon: fab fa-facebook
  - url: https://github.com/miloszpp
    fa_icon: fab fa-github
  - url: https://www.youtube.com/channel/UC_DEBDpgRyBZAT85tJ1QZBw
    fa_icon: fab fa-youtube
  - url: mailto:milosz@miloszpiechocki.com
    fa_icon: fas fa-envelope
  - url: /atom.xml
    fa_icon: fas fa-rss

# Footer about
footer_about: "@Copyright Miłosz Piechocki. All right reserved | Design & Hexo based on Anodyne by <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
